name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main   # ✅ change if your default branch is "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Upload only the "public" folder as the website content
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload frontend
        uses: actions/upload-pages-artifact@v3
        with:
          path: public   # ✅ deploy just public/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
